### ISSUE TITLE
Failed parse xunit xml format: suite.testcase is not iterable

### ISSUE THREAD

**Issue by abcfy2** [phoenix-actions/test-reporting#28]
Did you change any break changes? The xunit format is working with `jest-junit` before: https://github.com/DTeam-Top/st2/runs/8390250789#r0

But now it's break down:
![image](https://user-images.githubusercontent.com/5327677/203321189-4d7a0abc-512c-4791-98c9-f857ffd141b4.png)

Here is the sample generated by [tap-xunit](https://www.npmjs.com/package/tap-xunit)

```xml
<?xml version="1.0"?>
<testsuites>
  <testsuite tests="65" failures="0" errors="0" name="Default">
    <testcase name="#1 _core › services › jwtService › empty rule set should filter nothing"/>
    <testcase name="#2 _core › services › jwtService › only limited methods should be filered: GET"/>
    <testcase name="#3 _core › services › jwtService › only target url should be filtered: GET"/>
    <testcase name="#4 _core › services › jwtService › both patterns and methods in rules: GET"/>
    <testcase name="#5 _core › services › jwtService › only limited methods should be filered: POST"/>
    <testcase name="#6 _core › services › jwtService › only target url should be filtered: POST"/>
    <testcase name="#7 _core › services › jwtService › both patterns and methods in rules: POST"/>
    <testcase name="#8 _core › services › jwtService › only limited methods should be filered: PUT"/>
    <testcase name="#9 _core › services › jwtService › only target url should be filtered: PUT"/>
    <testcase name="#10 _core › services › jwtService › both patterns and methods in rules: PUT"/>
    <testcase name="#11 _core › services › jwtService › only limited methods should be filered: DELETE"/>
    <testcase name="#12 _core › services › jwtService › only target url should be filtered: DELETE"/>
    <testcase name="#13 _core › services › jwtService › both patterns and methods in rules: DELETE"/>
    <testcase name="#14 _core › services › jwtService › only limited methods should be filered: OPTIONS"/>
    <testcase name="#15 _core › services › jwtService › only target url should be filtered: OPTIONS"/>
    <testcase name="#16 _core › services › jwtService › both patterns and methods in rules: OPTIONS"/>
    <testcase name="#17 _core › services › jwtService › only limited methods should be filered: HEAD"/>
    <testcase name="#18 _core › services › jwtService › only target url should be filtered: HEAD"/>
    <testcase name="#19 _core › services › jwtService › both patterns and methods in rules: HEAD"/>
    <testcase name="#20 _core › services › jwtService › only limited methods should be filered: TRACE"/>
    <testcase name="#21 _core › services › jwtService › only target url should be filtered: TRACE"/>
    <testcase name="#22 _core › services › jwtService › both patterns and methods in rules: TRACE"/>
    <testcase name="#23 _core › services › jwtService › only limited methods should be filered: PATCH"/>
    <testcase name="#24 _core › services › jwtService › only target url should be filtered: PATCH"/>
    <testcase name="#25 _core › services › jwtService › both patterns and methods in rules: PATCH"/>
    <testcase name="#26 _core › services › jwtService › only limited methods should be filered: get"/>
    <testcase name="#27 _core › services › jwtService › only target url should be filtered: get"/>
    <testcase name="#28 _core › services › jwtService › both patterns and methods in rules: get"/>
    <testcase name="#29 _core › services › jwtService › only limited methods should be filered: post"/>
    <testcase name="#30 _core › services › jwtService › only target url should be filtered: post"/>
    <testcase name="#31 _core › services › jwtService › both patterns and methods in rules: post"/>
    <testcase name="#32 _core › services › jwtService › only limited methods should be filered: put"/>
    <testcase name="#33 _core › services › jwtService › only target url should be filtered: put"/>
    <testcase name="#34 _core › services › jwtService › both patterns and methods in rules: put"/>
    <testcase name="#35 _core › services › jwtService › only limited methods should be filered: delete"/>
    <testcase name="#36 _core › services › jwtService › only target url should be filtered: delete"/>
    <testcase name="#37 _core › services › jwtService › both patterns and methods in rules: delete"/>
    <testcase name="#38 _core › services › jwtService › only limited methods should be filered: options"/>
    <testcase name="#39 _core › services › jwtService › only target url should be filtered: options"/>
    <testcase name="#40 _core › services › jwtService › both patterns and methods in rules: options"/>
    <testcase name="#41 _core › services › jwtService › only limited methods should be filered: head"/>
    <testcase name="#42 _core › services › jwtService › only target url should be filtered: head"/>
    <testcase name="#43 _core › services › jwtService › both patterns and methods in rules: head"/>
    <testcase name="#44 _core › services › jwtService › only limited methods should be filered: trace"/>
    <testcase name="#45 _core › services › jwtService › only target url should be filtered: trace"/>
    <testcase name="#46 _core › services › jwtService › both patterns and methods in rules: trace"/>
    <testcase name="#47 _core › services › jwtService › only limited methods should be filered: patch"/>
    <testcase name="#48 _core › services › jwtService › only target url should be filtered: patch"/>
    <testcase name="#49 _core › services › jwtService › both patterns and methods in rules: patch"/>
    <testcase name="#50 _core › utils › common › unifyAddresses(0x3F1EcC900564b03C79716fef5FD62a676Fd9e61D) === 0x3F1EcC900564b03C79716fef5FD62a676Fd9e61D"/>
    <testcase name="#51 _core › utils › common › unifyAddresses(0X3F1ECC900564B03C79716FEF5FD62A676FD9E61D) === 0x3F1EcC900564b03C79716fef5FD62a676Fd9e61D"/>
    <testcase name="#52 _core › utils › common › unifyAddresses(0x3f1ecc900564b03c79716fef5fd62a676fd9e61d) === 0x3F1EcC900564b03C79716fef5FD62a676Fd9e61D"/>
    <testcase name="#53 _core › utils › common › unifyAddresses(0x3f1ECC900564b03c79716FEF5fd62a676fd9e61d) === 0x3F1EcC900564b03C79716fef5FD62a676Fd9e61D"/>
    <testcase name="#54 _core › utils › common › toHttpUrl should not change http based urls"/>
    <testcase name="#55 _core › utils › common › toHttpUrl should change ipfs based urls"/>
    <testcase name="#56 _core › utils › common › toHttpUrl should throw exception for non ipfs or http urls"/>
    <testcase name="#57 _core › utils › common › sameAddresses should work"/>
    <testcase name="#58 _core › utils › common › sameAddresses should not work for non-address strings"/>
    <testcase name="#59 _core › utils › common › parseUnits / unitsOf should work"/>
    <testcase name="#60 _core › utils › common › truncateNumber should work"/>
    <testcase name="#61 _core › utils › common › truncate should not work for non-number strings"/>
    <testcase name="#62 _core › utils › common › truncate should not work for invalid precision."/>
    <testcase name="#63 _core › controller › route › route should work"/>
    <testcase name="#64 _core › controller › route › jwtVerifier should work"/>
    <testcase name="#65 controller › actions › /health should work">
      <system-out>{"level":30,"time":1669120617874,"pid":44781,"hostname":"fengyu-laptop-mj","reqId":"req-1","req":{"method":"GET","url":"/test","hostname":"localhost:80","remoteAddress":"127.0.0.1"},"msg":"incoming request"}
</system-out>
      <system-out>{"level":30,"time":1669120617876,"pid":44781,"hostname":"fengyu-laptop-mj","reqId":"req-2","req":{"method":"GET","url":"/protected/test","hostname":"localhost:80","remoteAddress":"127.0.0.1"},"msg":"incoming request"}
</system-out>
      <system-out>{"level":30,"time":1669120617876,"pid":44781,"hostname":"fengyu-laptop-mj","msg":"Server successfully booted!"}
</system-out>
      <system-out>{"level":30,"time":1669120617879,"pid":44781,"hostname":"fengyu-laptop-mj","reqId":"req-1","res":{"statusCode":200},"responseTime":3.396286003291607,"msg":"request completed"}
</system-out>
      <system-out>{"level":30,"time":1669120617879,"pid":44781,"hostname":"fengyu-laptop-mj","reqId":"req-2","res":{"statusCode":200},"responseTime":3.0541130006313324,"msg":"request completed"}
</system-out>
      <system-out>{"level":30,"time":1669120617879,"pid":44781,"hostname":"fengyu-laptop-mj","reqId":"req-3","req":{"method":"POST","url":"/sub/test","hostname":"localhost:80","remoteAddress":"127.0.0.1"},"msg":"incoming request"}
</system-out>
      <system-out>{"level":30,"time":1669120617880,"pid":44781,"hostname":"fengyu-laptop-mj","reqId":"req-4","req":{"method":"POST","url":"/protected/test","hostname":"localhost:80","remoteAddress":"127.0.0.1"},"msg":"incoming request"}
</system-out>
      <system-out>{"level":30,"time":1669120617880,"pid":44781,"hostname":"fengyu-laptop-mj","reqId":"req-4","res":{"statusCode":401},"err":{"type":"FastifyError","message":"No Authorization was found in request.headers","stack":"FastifyError: No Authorization was found in request.headers\n    at lookupToken (/home/fengyu/projects/AlphaWallet/quick-eth/apps/api/node_modules/@fastify/jwt/jwt.js:241:13)\n    at _Request.requestVerify [as jwtVerify] (/home/fengyu/projects/AlphaWallet/quick-eth/apps/api/node_modules/@fastify/jwt/jwt.js:446:15)\n    at /home/fengyu/projects/AlphaWallet/quick-eth/apps/api/node_modules/@fastify/jwt/jwt.js:438:31\n    at new Promise (&lt;anonymous&gt;)\n    at _Request.requestVerify [as jwtVerify] (/home/fengyu/projects/AlphaWallet/quick-eth/apps/api/node_modules/@fastify/jwt/jwt.js:437:14)\n    at Object.&lt;anonymous&gt; (/home/fengyu/projects/AlphaWallet/quick-eth/apps/api/src/_core/controller/route.ts:35:44)\n    at hookIterator (/home/fengyu/projects/AlphaWallet/quick-eth/apps/api/node_modules/fastify/lib/hooks.js:246:10)\n    at next (/home/fengyu/projects/AlphaWallet/quick-eth/apps/api/node_modules/fastify/lib/hooks.js:174:16)\n    at Object.&lt;anonymous&gt; (/home/fengyu/projects/AlphaWallet/quick-eth/apps/api/node_modules/@fastify/awilix/lib/fastifyAwilixPlugin.js:17:5)\n    at hookIterator (/home/fengyu/projects/AlphaWallet/quick-eth/apps/api/node_modules/fastify/lib/hooks.js:246:10)","name":"FastifyError","code":"FST_JWT_NO_AUTHORIZATION_IN_HEADER","statusCode":401},"msg":"No Authorization was found in request.headers"}
</system-out>
      <system-out>{"level":30,"time":1669120617884,"pid":44781,"hostname":"fengyu-laptop-mj","reqId":"req-3","res":{"statusCode":201},"responseTime":0.7220579981803894,"msg":"request completed"}
</system-out>
      <system-out>{"level":30,"time":1669120617884,"pid":44781,"hostname":"fengyu-laptop-mj","reqId":"req-4","res":{"statusCode":401},"responseTime":4.603818003088236,"msg":"request completed"}
</system-out>
      <system-out>{"level":30,"time":1669120617885,"pid":44781,"hostname":"fengyu-laptop-mj","reqId":"req-5","req":{"method":"POST","url":"/protected/test","hostname":"localhost:80","remoteAddress":"127.0.0.1"},"msg":"incoming request"}
</system-out>
      <system-out>{"level":30,"time":1669120617886,"pid":44781,"hostname":"fengyu-laptop-mj","reqId":"req-5","res":{"statusCode":401},"err":{"type":"FastifyError","message":"Authorization token is invalid: The token signature is invalid.","stack":"FastifyError: Authorization token is invalid: The token signature is invalid.\n    at verify (/home/fengyu/projects/AlphaWallet/quick-eth/apps/api/node_modules/@fastify/jwt/jwt.js:481:17)\n    at work (/home/fengyu/projects/AlphaWallet/quick-eth/apps/api/node_modules/fastfall/fall.js:105:23)\n    at /home/fengyu/projects/AlphaWallet/quick-eth/apps/api/node_modules/@fastify/jwt/jwt.js:22:12\n    at getSecret (/home/fengyu/projects/AlphaWallet/quick-eth/apps/api/node_modules/@fastify/jwt/jwt.js:455:30)\n    at Holder.work (/home/fengyu/projects/AlphaWallet/quick-eth/apps/api/node_modules/fastfall/fall.js:103:23)\n    at Function.fall [as waterfall] (/home/fengyu/projects/AlphaWallet/quick-eth/apps/api/node_modules/fastfall/fall.js:30:13)\n    at _Request.requestVerify [as jwtVerify] (/home/fengyu/projects/AlphaWallet/quick-eth/apps/api/node_modules/@fastify/jwt/jwt.js:453:11)\n    at /home/fengyu/projects/AlphaWallet/quick-eth/apps/api/node_modules/@fastify/jwt/jwt.js:438:31\n    at new Promise (&lt;anonymous&gt;)\n    at _Request.requestVerify [as jwtVerify] (/home/fengyu/projects/AlphaWallet/quick-eth/apps/api/node_modules/@fastify/jwt/jwt.js:437:14)","name":"FastifyError","code":"FST_JWT_AUTHORIZATION_TOKEN_INVALID","statusCode":401},"msg":"Authorization token is invalid: The token signature is invalid."}
</system-out>
      <system-out>{"level":30,"time":1669120617887,"pid":44781,"hostname":"fengyu-laptop-mj","reqId":"req-5","res":{"statusCode":401},"responseTime":2.082396000623703,"msg":"request completed"}
</system-out>
      <system-out>{"level":30,"time":1669120617887,"pid":44781,"hostname":"fengyu-laptop-mj","reqId":"req-6","req":{"method":"POST","url":"/protected/test","hostname":"localhost:80","remoteAddress":"127.0.0.1"},"msg":"incoming request"}
</system-out>
      <system-out>{"level":30,"time":1669120617887,"pid":44781,"hostname":"fengyu-laptop-mj","reqId":"req-6","res":{"statusCode":201},"responseTime":0.3499779999256134,"msg":"request completed"}
</system-out>
      <system-out>{"level":30,"time":1669120617888,"pid":44781,"hostname":"fengyu-laptop-mj","reqId":"req-7","req":{"method":"GET","url":"/banned-all/test","hostname":"localhost:80","remoteAddress":"127.0.0.1"},"msg":"incoming request"}
</system-out>
      <system-out>{"level":30,"time":1669120617888,"pid":44781,"hostname":"fengyu-laptop-mj","reqId":"req-8","req":{"method":"POST","url":"/banned-all/test","hostname":"localhost:80","remoteAddress":"127.0.0.1"},"msg":"incoming request"}
</system-out>
      <system-out>{"level":30,"time":1669120617888,"pid":44781,"hostname":"fengyu-laptop-mj","reqId":"req-9","req":{"method":"DELETE","url":"/banned-all/test","hostname":"localhost:80","remoteAddress":"127.0.0.1"},"msg":"incoming request"}
</system-out>
      <system-out>{"level":30,"time":1669120617888,"pid":44781,"hostname":"fengyu-laptop-mj","reqId":"req-a","req":{"method":"GET","url":"/banned-all/test","hostname":"localhost:80","remoteAddress":"127.0.0.1"},"msg":"incoming request"}
</system-out>
      <system-out>{"level":30,"time":1669120617888,"pid":44781,"hostname":"fengyu-laptop-mj","reqId":"req-b","req":{"method":"POST","url":"/banned-all/test","hostname":"localhost:80","remoteAddress":"127.0.0.1"},"msg":"incoming request"}
</system-out>
      <system-out>{"level":30,"time":1669120617888,"pid":44781,"hostname":"fengyu-laptop-mj","reqId":"req-c","req":{"method":"DELETE","url":"/banned-all/test","hostname":"localhost:80","remoteAddress":"127.0.0.1"},"msg":"incoming request"}
</system-out>
      <system-out>{"level":30,"time":1669120617888,"pid":44781,"hostname":"fengyu-laptop-mj","reqId":"req-7","res":{"statusCode":401},"err":{"type":"FastifyError","message":"No Authorization was found in request.headers","stack":"FastifyError: No Authorization was found in request.headers\n    at lookupToken (/home/fengyu/projects/AlphaWallet/quick-eth/apps/api/node_modules/@fastify/jwt/jwt.js:241:13)\n    at _Request.requestVerify [as jwtVerify] (/home/fengyu/projects/AlphaWallet/quick-eth/apps/api/node_modules/@fastify/jwt/jwt.js:446:15)\n    at /home/fengyu/projects/AlphaWallet/quick-eth/apps/api/node_modules/@fastify/jwt/jwt.js:438:31\n    at new Promise (&lt;anonymous&gt;)\n    at _Request.requestVerify [as jwtVerify] (/home/fengyu/projects/AlphaWallet/quick-eth/apps/api/node_modules/@fastify/jwt/jwt.js:437:14)\n    at Object.&lt;anonymous&gt; (/home/fengyu/projects/AlphaWallet/quick-eth/apps/api/src/_core/controller/route.ts:35:44)\n    at hookIterator (/home/fengyu/projects/AlphaWallet/quick-eth/apps/api/node_modules/fastify/lib/hooks.js:246:10)\n    at next (/home/fengyu/projects/AlphaWallet/quick-eth/apps/api/node_modules/fastify/lib/hooks.js:174:16)\n    at Object.&lt;anonymous&gt; (/home/fengyu/projects/AlphaWallet/quick-eth/apps/api/node_modules/@fastify/awilix/lib/fastifyAwilixPlugin.js:17:5)\n    at hookIterator (/home/fengyu/projects/AlphaWallet/quick-eth/apps/api/node_modules/fastify/lib/hooks.js:246:10)","name":"FastifyError","code":"FST_JWT_NO_AUTHORIZATION_IN_HEADER","statusCode":401},"msg":"No Authorization was found in request.headers"}
</system-out>
      <system-out>{"level":30,"time":1669120617889,"pid":44781,"hostname":"fengyu-laptop-mj","reqId":"req-8","res":{"statusCode":401},"err":{"type":"FastifyError","message":"No Authorization was found in request.headers","stack":"FastifyError: No Authorization was found in request.headers\n    at lookupToken (/home/fengyu/projects/AlphaWallet/quick-eth/apps/api/node_modules/@fastify/jwt/jwt.js:241:13)\n    at _Request.requestVerify [as jwtVerify] (/home/fengyu/projects/AlphaWallet/quick-eth/apps/api/node_modules/@fastify/jwt/jwt.js:446:15)\n    at /home/fengyu/projects/AlphaWallet/quick-eth/apps/api/node_modules/@fastify/jwt/jwt.js:438:31\n    at new Promise (&lt;anonymous&gt;)\n    at _Request.requestVerify [as jwtVerify] (/home/fengyu/projects/AlphaWallet/quick-eth/apps/api/node_modules/@fastify/jwt/jwt.js:437:14)\n    at Object.&lt;anonymous&gt; (/home/fengyu/projects/AlphaWallet/quick-eth/apps/api/src/_core/controller/route.ts:35:44)\n    at hookIterator (/home/fengyu/projects/AlphaWallet/quick-eth/apps/api/node_modules/fastify/lib/hooks.js:246:10)\n    at next (/home/fengyu/projects/AlphaWallet/quick-eth/apps/api/node_modules/fastify/lib/hooks.js:174:16)\n    at Object.&lt;anonymous&gt; (/home/fengyu/projects/AlphaWallet/quick-eth/apps/api/node_modules/@fastify/awilix/lib/fastifyAwilixPlugin.js:17:5)\n    at hookIterator (/home/fengyu/projects/AlphaWallet/quick-eth/apps/api/node_modules/fastify/lib/hooks.js:246:10)","name":"FastifyError","code":"FST_JWT_NO_AUTHORIZATION_IN_HEADER","statusCode":401},"msg":"No Authorization was found in request.headers"}
</system-out>
      <system-out>{"level":30,"time":1669120617889,"pid":44781,"hostname":"fengyu-laptop-mj","reqId":"req-9","res":{"statusCode":401},"err":{"type":"FastifyError","message":"No Authorization was found in request.headers","stack":"FastifyError: No Authorization was found in request.headers\n    at lookupToken (/home/fengyu/projects/AlphaWallet/quick-eth/apps/api/node_modules/@fastify/jwt/jwt.js:241:13)\n    at _Request.requestVerify [as jwtVerify] (/home/fengyu/projects/AlphaWallet/quick-eth/apps/api/node_modules/@fastify/jwt/jwt.js:446:15)\n    at /home/fengyu/projects/AlphaWallet/quick-eth/apps/api/node_modules/@fastify/jwt/jwt.js:438:31\n    at new Promise (&lt;anonymous&gt;)\n    at _Request.requestVerify [as jwtVerify] (/home/fengyu/projects/AlphaWallet/quick-eth/apps/api/node_modules/@fastify/jwt/jwt.js:437:14)\n    at Object.&lt;anonymous&gt; (/home/fengyu/projects/AlphaWallet/quick-eth/apps/api/src/_core/controller/route.ts:35:44)\n    at hookIterator (/home/fengyu/projects/AlphaWallet/quick-eth/apps/api/node_modules/fastify/lib/hooks.js:246:10)\n    at next (/home/fengyu/projects/AlphaWallet/quick-eth/apps/api/node_modules/fastify/lib/hooks.js:174:16)\n    at Object.&lt;anonymous&gt; (/home/fengyu/projects/AlphaWallet/quick-eth/apps/api/node_modules/@fastify/awilix/lib/fastifyAwilixPlugin.js:17:5)\n    at hookIterator (/home/fengyu/projects/AlphaWallet/quick-eth/apps/api/node_modules/fastify/lib/hooks.js:246:10)","name":"FastifyError","code":"FST_JWT_NO_AUTHORIZATION_IN_HEADER","statusCode":401},"msg":"No Authorization was found in request.headers"}
</system-out>
      <system-out>{"level":30,"time":1669120617890,"pid":44781,"hostname":"fengyu-laptop-mj","reqId":"req-7","res":{"statusCode":401},"responseTime":1.2324169985949993,"msg":"request completed"}
</system-out>
      <system-out>{"level":30,"time":1669120617890,"pid":44781,"hostname":"fengyu-laptop-mj","reqId":"req-8","res":{"statusCode":401},"responseTime":1.4230160005390644,"msg":"request completed"}
</system-out>
      <system-out>{"level":30,"time":1669120617890,"pid":44781,"hostname":"fengyu-laptop-mj","reqId":"req-9","res":{"statusCode":401},"responseTime":1.6336320005357265,"msg":"request completed"}
</system-out>
      <system-out>{"level":30,"time":1669120617890,"pid":44781,"hostname":"fengyu-laptop-mj","reqId":"req-a","res":{"statusCode":200},"responseTime":1.6284230016171932,"msg":"request completed"}
</system-out>
      <system-out>{"level":30,"time":1669120617890,"pid":44781,"hostname":"fengyu-laptop-mj","reqId":"req-b","res":{"statusCode":200},"responseTime":1.4986380003392696,"msg":"request completed"}
</system-out>
      <system-out>{"level":30,"time":1669120617890,"pid":44781,"hostname":"fengyu-laptop-mj","reqId":"req-c","res":{"statusCode":200},"responseTime":1.3942120000720024,"msg":"request completed"}
</system-out>
      <system-out>{"level":30,"time":1669120617892,"pid":44781,"hostname":"fengyu-laptop-mj","reqId":"req-1","req":{"method":"GET","url":"/health","hostname":"localhost:80","remoteAddress":"127.0.0.1"},"msg":"incoming request"}
</system-out>
      <system-out>{"level":30,"time":1669120617896,"pid":44781,"hostname":"fengyu-laptop-mj","msg":"Server successfully booted!"}
</system-out>
      <system-out>{"level":30,"time":1669120617896,"pid":44781,"hostname":"fengyu-laptop-mj","reqId":"req-1","res":{"statusCode":200},"responseTime":3.0050409995019436,"msg":"request completed"}
</system-out>
      <system-out>{"level":50,"time":1669120623733,"pid":44781,"hostname":"fengyu-laptop-mj","from":"DbService","err":{"type":"DatabaseError","message":"syntax error at or near \")\"","stack":"error: syntax error at or near \")\"\n    at Parser.parseErrorMessage (/home/fengyu/projects/AlphaWallet/quick-eth/apps/api/node_modules/pg-protocol/src/parser.ts:369:69)\n    at Parser.handlePacket (/home/fengyu/projects/AlphaWallet/quick-eth/apps/api/node_modules/pg-protocol/src/parser.ts:188:21)\n    at Parser.parse (/home/fengyu/projects/AlphaWallet/quick-eth/apps/api/node_modules/pg-protocol/src/parser.ts:103:30)\n    at Socket.&lt;anonymous&gt; (/home/fengyu/projects/AlphaWallet/quick-eth/apps/api/node_modules/pg-protocol/src/index.ts:7:48)\n    at Socket.emit (node:events:513:28)\n    at Socket.emit (node:domain:489:12)\n    at addChunk (node:internal/streams/readable:324:12)\n    at readableAddChunk (node:internal/streams/readable:297:9)\n    at Socket.Readable.push (node:internal/streams/readable:234:10)\n    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)","length":90,"name":"error","severity":"ERROR","code":"42601","position":"69","file":"scan.l","line":"1176","routine":"scanner_yyerror"},"msg":"executing sql: \n    CREATE TABLE table1 (\n        id    serial,\n        name  \n    )\n    , args: [], caused: syntax error at or near \")\""}
</system-out>
      <system-out>{"level":50,"time":1669120623744,"pid":44781,"hostname":"fengyu-laptop-mj","from":"DbService","err":{"type":"DatabaseError","message":"relation \"table2\" does not exist","stack":"error: relation \"table2\" does not exist\n    at Parser.parseErrorMessage (/home/fengyu/projects/AlphaWallet/quick-eth/apps/api/node_modules/pg-protocol/src/parser.ts:369:69)\n    at Parser.handlePacket (/home/fengyu/projects/AlphaWallet/quick-eth/apps/api/node_modules/pg-protocol/src/parser.ts:188:21)\n    at Parser.parse (/home/fengyu/projects/AlphaWallet/quick-eth/apps/api/node_modules/pg-protocol/src/parser.ts:103:30)\n    at Socket.&lt;anonymous&gt; (/home/fengyu/projects/AlphaWallet/quick-eth/apps/api/node_modules/pg-protocol/src/index.ts:7:48)\n    at Socket.emit (node:events:513:28)\n    at Socket.emit (node:domain:489:12)\n    at addChunk (node:internal/streams/readable:324:12)\n    at readableAddChunk (node:internal/streams/readable:297:9)\n    at Socket.Readable.push (node:internal/streams/readable:234:10)\n    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)","length":105,"name":"error","severity":"ERROR","code":"42P01","position":"22","file":"parse_relation.c","line":"1373","routine":"parserOpenTable"},"msg":"executing sql: select count(*) from table2, args: [], caused: relation \"table2\" does not exist"}
</system-out>
    </testcase>
  </testsuite>
  <testsuite tests="2" failures="0" errors="0" name="_core › services › dbService › before hook">
    <testcase name="#66 _core › services › dbService › DbService should work: positive cases."/>
    <testcase name="#67 _core › services › dbService › DbService should work: negative cases.">
      <system-out>{"level":50,"time":1669120623747,"pid":44781,"hostname":"fengyu-laptop-mj","from":"DbService","err":{"type":"DatabaseError","message":"relation \"table2\" does not exist","stack":"error: relation \"table2\" does not exist\n    at Parser.parseErrorMessage (/home/fengyu/projects/AlphaWallet/quick-eth/apps/api/node_modules/pg-protocol/src/parser.ts:369:69)\n    at Parser.handlePacket (/home/fengyu/projects/AlphaWallet/quick-eth/apps/api/node_modules/pg-protocol/src/parser.ts:188:21)\n    at Parser.parse (/home/fengyu/projects/AlphaWallet/quick-eth/apps/api/node_modules/pg-protocol/src/parser.ts:103:30)\n    at Socket.&lt;anonymous&gt; (/home/fengyu/projects/AlphaWallet/quick-eth/apps/api/node_modules/pg-protocol/src/index.ts:7:48)\n    at Socket.emit (node:events:513:28)\n    at Socket.emit (node:domain:489:12)\n    at addChunk (node:internal/streams/readable:324:12)\n    at readableAddChunk (node:internal/streams/readable:297:9)\n    at Socket.Readable.push (node:internal/streams/readable:234:10)\n    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)","length":105,"name":"error","severity":"ERROR","code":"42P01","position":"22","file":"parse_relation.c","line":"1373","routine":"parserOpenTable"},"msg":"executing sql: select count(*) from table2, args: [], caused: relation \"table2\" does not exist"}
</system-out>
      <system-out>{"level":50,"time":1669120623749,"pid":44781,"hostname":"fengyu-laptop-mj","from":"DbService","err":{"type":"DatabaseError","message":"null value in column \"name\" of relation \"table2\" violates not-null constraint","stack":"error: null value in column \"name\" of relation \"table2\" violates not-null constraint\n    at Parser.parseErrorMessage (/home/fengyu/projects/AlphaWallet/quick-eth/apps/api/node_modules/pg-protocol/src/parser.ts:369:69)\n    at Parser.handlePacket (/home/fengyu/projects/AlphaWallet/quick-eth/apps/api/node_modules/pg-protocol/src/parser.ts:188:21)\n    at Parser.parse (/home/fengyu/projects/AlphaWallet/quick-eth/apps/api/node_modules/pg-protocol/src/parser.ts:103:30)\n    at Socket.&lt;anonymous&gt; (/home/fengyu/projects/AlphaWallet/quick-eth/apps/api/node_modules/pg-protocol/src/index.ts:7:48)\n    at Socket.emit (node:events:513:28)\n    at Socket.emit (node:domain:489:12)\n    at addChunk (node:internal/streams/readable:324:12)\n    at readableAddChunk (node:internal/streams/readable:297:9)\n    at Socket.Readable.push (node:internal/streams/readable:234:10)\n    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)","length":195,"name":"error","severity":"ERROR","code":"23502","detail":"Failing row contains (2, null).","schema":"public","table":"table2","column":"name","file":"execMain.c","line":"1947","routine":"ExecConstraints"},"msg":"executing transactions error. queries: [{\"sql\":\"\\n    insert into table2 (name) values ($1)\\n  \",\"params\":[\"name1\"]},{\"sql\":\"\\n    insert into table2 (name) values ($1)\\n  \",\"params\":[null]}], caused: null value in column \"name\" of relation \"table2\" violates not-null constraint"}
</system-out>
    </testcase>
  </testsuite>
  <testsuite tests="0" failures="0" errors="0" name="_core › services › dbService › after hook"/>
</testsuites>
```

**Comment by IanMoroney** [comment]
@abcfy2 , we're now on v10. Can you try that to see if it works?
Alternatively, does it work on v7?

**Comment by abcfy2** [comment]
Seems it's work now.
